### ISSUE TITLE
the message "lost Х liters of water" appears

### ISSUE THREAD

**Issue by DayZTLD** [WulfMarius/Better-Water-Management#10]
Better-Water-Management 3.0.1
after cooking water in a pot, when you go through the locations between locations (between the location and the house), the message "Х liters of water is lost" appears... |where 'X' is the amount of drinking water in the inventory| The message appears constantly!
Installed modifications:
<a href="https://jpegshare.net/96/41/9641a81f478001d1ac375aca760e19f2.jpg.html" target="_blank" title="JpegShare.net - бесплатный хостинг картинок"><img src="https://jpegshare.net/thumbs/96/41/9641a81f478001d1ac375aca760e19f2.jpg"/><a>

Thank you for your modifications, the game has become better with them!

**Comment by WulfMarius** [comment]
I can reproduce this and will take a look.
Thanks for reporting!

**Comment by WulfMarius** [comment]
The issue should be fixed with version 3.0.2
