### ISSUE TITLE
Pots Spawning

### ISSUE THREAD

**Issue by hwn2020** [WulfMarius/Better-Water-Management#3]
TLD v.1.15

In the PV farmhouse there is a pot on the counter in the kitchen.  If you select it to pick it up, but cancel the action after viewing it, it spawns a pot on the floor directly behind you 10ft or so on the floor in the house.

I tested it, and no matter if it is a pot or a pan or which one you actually view, they always spawn a new pot and pan on the floor when you view one.

![the long dark screenshot 2017 12 05 - 20 51 38 94](https://user-images.githubusercontent.com/33557014/33644054-d98a7950-d9ff-11e7-9677-a2df73df7273.png)
![the long dark screenshot 2017 12 05 - 20 51 54 20](https://user-images.githubusercontent.com/33557014/33644056-d9a5057c-d9ff-11e7-8af5-b9ed3110d7ef.png)

**Comment by WulfMarius** [comment]
Confirmed and fixed in master.
Will be part of the 1.0.2 release.

Thanks for spotting and reporting!
