### ISSUE TITLE
water bottle color

### ISSUE THREAD

**Issue by Cryinghawke** [WulfMarius/Better-Water-Management#5]
is it possible to add a green tint to water bottles to prevent confusion between potable and not potable?

**Comment by WulfMarius** [comment]
Do mean in the inventory or in the 3d world or both?

Inventory and UI would be very simple.
3d will require some additional work, but it shouldn't be that much.

**Comment by Cryinghawke** [comment]
the inventory and UI used to have a green bottle for not potable and the 3d for potable and not potable was always the same

**Comment by stevendolg** [comment]
I already started working on this yesterday:

* Bottles containing non-potable water get a yellow/green-ish tint.
* Bottles containing potable water get the default look.
* Empty bottles will look brighter and get their own sound effect.

With good light they should all be clearly recognizable by just looking at them, both in the inventory and 3d world.  
Should be done some time this week.

**Comment by WulfMarius** [comment]
I already started working on this yesterday:

* Bottles containing non-potable water get a yellow/green-ish tint.
* Bottles containing potable water get the default look.
* Empty bottles will look brighter and get their own sound effect.

With good light they should all be clearly recognizable by just looking at them, both in the inventory and 3d world.  
Should be done some time this week.

**Comment by WulfMarius** [comment]
This is now part of version 1.0.5
