### ISSUE TITLE
miniature pot?

### ISSUE THREAD

**Issue by Cryinghawke** [WulfMarius/Better-Water-Management#6]
![20180218034809_1](https://user-images.githubusercontent.com/34219174/36347700-9a8317ac-1466-11e8-953b-2287e4ce7ab8.jpg)

same pot i've had since i first picked it up in ML next to a 0.5L bottle. I swear it used to be normal size XD

**Comment by WulfMarius** [comment]
People have been posting screenshots of miniaturized items for quite some time now. I guess this is a bug in the game's original code, that can also "infect" modded items.

Do you happen to know when/how this started?  
Does it reset its size after reloading the game?

I'd like to wait for Hinterland's next bug fix release and see if that corrects things.  
It's probably hard to replicate.

If you still have that savegame it might be worth a try to take a look at it.

**Comment by Cryinghawke** [comment]
i'll look over my pot collection see if other pots also have this issue. it seems to persists after game shutdown. i don't really mind it. it's cute. just thought you should know.
