### ISSUE TITLE
Better Water Management 2.4.1

### ISSUE THREAD

**Issue by DayZTLD** [WulfMarius/Better-Water-Management#9]
After the release of version 2.4.1 modification BWM, the use of water purification tablets stopped working, checked several times, the game TLD -> version 1.40 / BWM v 2.4.0 work! /

**Comment by WulfMarius** [comment]
Version 2.5.0 should fix this one.

Thanks for reporting!

**Comment by DayZTLD** [comment]
Thanks to you for doing what the game developers had to do three years ago!
Why remove the phenomenon when the water continues to boil in the bank? !! It was beautiful)) (joke)
